version: '3'
services:
  app:
    build: .
    volumes:
      - ./test:/app/test
    entrypoint: watchmedo auto-restart --recursive --pattern="*.csv" --directory="./test" python testing-docker.py
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M